### ISSUE TITLE
add example for resources and dependency property

### ISSUE THREAD

**Issue by harvinders** [dnchattan/winui-extensions#1]
You mentioned that you were able to make dependency properties work in a limited fashion, could you add an example in this repo? 

Also were you able to use string resources from the resource file in the xaml file using x:Uid? That example would also be valuable.

**Comment by dnchattan** [comment]
I've just added some example code for a simple enum dependency property here:
https://github.com/dnchattan/winui-extensions/blob/ba88c46e9275023273d3327d612ecbc2a17192b1/SampleExtension/UI/Greeter.xaml.cs#L43

Will take a look into string resources and see if they work correctly or not

**Comment by dnchattan** [comment]
so far no luck on string resources. based on procexp, I can't even get the runtime to look for a resources.pri file on disk much less open it.

**Comment by dnchattan** [comment]
I can't get `x:Uid` to work no matter how much everything else seems to be doing the right things, however I do have the resources at least loading and accessible programmatically. 

See #2 for the example added to `Greeter.xaml.cs` to assign the resource value from codebehind.
